KERNEL_DIR=/android/thug/del
KERN_IMG=$KERNEL_DIR/arch/arm64/boot/Image
DTBTOOL=$KERNEL_DIR/tools/dtbToolCM
TOOLCHAIN_DIR=~/android/tc/ub-opt/bin
export ARCH=arm64
# export CCOMPILE=$CROSS_COMPILE
# export CROSS_COMPILE=aarch64-linux-android-
export CROSS_COMPILE=/android/thug/tc/ub-opt/bin/aarch64-linux-android-
export PATH=$PATH:~/android/thug/tc/ub-opt/bin
export KBUILD_BUILD_USER="DroidThug"
export KBUILD_BUILD_HOST="EvoqueUnit"
STRIP="/android/thug/tc/ub-opt/bin/aarch64-linux-android-strip"
MODULES_DIR=$KERNEL_DIR/drivers/staging/prima
